<?xml version="1.0"?>
<wsdl:definitions
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://www.jboss.org/eap/quickstarts/wscalculator/Calculator"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:ns1="http://schemas.xmlsoap.org/soap/http"
    name="CalculatorService"
    targetNamespace="http://www.jboss.org/eap/quickstarts/wscalculator/Calculator">

    <wsdl:types>
        <xsd:schema
            targetNamespace="http://www.jboss.org/eap/quickstarts/wscalculator/Calculator">
            <xsd:include schemaLocation="calculator.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="add">
        <wsdl:part element="tns:add" name="add">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="addResponse">
        <wsdl:part element="tns:addResponse" name="addResponse">
        </wsdl:part>
    </wsdl:message>

    <wsdl:portType name="CalculatorService">
        <wsdl:operation name="add">
            <wsdl:input message="tns:add" name="add">
            </wsdl:input>
            <wsdl:output message="tns:addResponse" name="addResponse">
            </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="CalculatorServiceSoapBinding" type="tns:CalculatorService">
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http"></soap:binding>
        <wsdl:operation name="add">
            <soap:operation soapAction="" style="document"></soap:operation>
            <wsdl:input name="add">
                <soap:body use="literal"></soap:body>
            </wsdl:input>
            <wsdl:output name="addResponse">
                <soap:body use="literal"></soap:body>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CalculatorService">
        <wsdl:port binding="tns:CalculatorServiceSoapBinding" name="Calculator">
            <soap:address location="http://foo:8080/calculator-ws"></soap:address>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>