name: build-and-run-jvm-tests
description: 'Build the project and run JVM tests'

inputs:
  java-version:
    description: 'Java version'
    required: true
    
runs:
  using: 'composite'
  steps:

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}

    - name: Build CXF
      if: github.ref == 'refs/heads/cxf-main' || github.base_ref == 'cxf-main' || github.head_ref == 'cxf-main'
      uses: ./.github/actions/rebuild-dependency
      id: rebuild-cxf
      with:
        dependency-git-repo-url: https://github.com/apache/cxf.git
        dependency-short-name: cxf
    - name: Build Quarkus
      if: github.ref == 'refs/heads/quarkus-main' || github.base_ref == 'quarkus-main' || github.head_ref == 'quarkus-main'
      uses: ./.github/actions/rebuild-dependency
      id: rebuild-quarkus
      with:
        dependency-git-repo-url: https://github.com/quarkusio/quarkus.git
        dependency-short-name: quarkus

    - name: Ensure mvn cq:sync-versions -N causes no changes
      shell: bash
      run: |
        ./mvnw cq:sync-versions -Dcq.simpleElementWhitespace=AUTODETECT_PREFER_SPACE -N -ntp
        [[ -z $(git status --porcelain | grep -v antora.yml) ]] || { echo 'There are uncommitted changes'; git status; git diff; exit 1; }

    - name: mvn -B formatter:validate install
      shell: bash
      run: ./mvnw -B formatter:validate install -DskipTests -Dquarkus.build.skip -fae -ntp

    - name: mvn -B formatter:validate install
      shell: bash
      run: |
        cd integration-tests/fastinfoset
        for i in {1..50}; do    echo "==== run $i";  ../../mvnw test -Dtest=FastInfosetTest#fastInfosetNative;  done

