name: Build

on:
  pull_request:
    paths-ignore:
      - '.github/project.yml'

env:
  QUARKUS_CXF_MTOM_LARGE_ATTACHMENT_INCREMENT_KB: 512
  JAVA_VERSION: 17

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-run-jvm-tests:
    if: startsWith(github.head_ref, 'trigger-release-') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: build-and-run-jvm-tests
      uses: ./.github/actions/build-and-run-jvm-tests
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: cd integration-tests/client-server && mvn test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
      shell: bash
      run: |
        cd integration-tests/client-server
        for i in {1..100}; do
           echo ""
           echo "========================"
           echo "== Run $i"
           echo "========================"
           echo ""
           ../../mvnw clean test -Dtest=RedirectTest
        done
