name: Build

on:
  pull_request:
    paths-ignore:
      - '.github/project.yml'

env:
  QUARKUS_CXF_MTOM_LARGE_ATTACHMENT_INCREMENT_KB: 512
  JAVA_VERSION: 17

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-run-jvm-tests:
    if: startsWith(github.head_ref, 'trigger-release-') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: build-and-run-jvm-tests
      uses: ./.github/actions/build-and-run-jvm-tests
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: 1 cd integration-tests/client-server && mvn test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
      shell: bash
      run: cd integration-tests/client-server && ../../mvnw test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m

    - name: 2 cd integration-tests/client-server && mvn test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
      shell: bash
      run: cd integration-tests/client-server && ../../mvnw test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m

    - name: 3 cd integration-tests/client-server && mvn test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
      shell: bash
      run: cd integration-tests/client-server && ../../mvnw test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m

    - name: 4 cd integration-tests/client-server && mvn test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
      shell: bash
      run: cd integration-tests/client-server && ../../mvnw test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m

    - name: 5 cd integration-tests/client-server && mvn test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
      shell: bash
      run: cd integration-tests/client-server && ../../mvnw test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m

    - name: 6 cd integration-tests/client-server && mvn test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
      shell: bash
      run: cd integration-tests/client-server && ../../mvnw test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m

    - name: 7 cd integration-tests/client-server && mvn test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
      shell: bash
      run: cd integration-tests/client-server && ../../mvnw test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m

    - name: 8 cd integration-tests/client-server && mvn test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
      shell: bash
      run: cd integration-tests/client-server && ../../mvnw test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m

    - name: 9 cd integration-tests/client-server && mvn test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
      shell: bash
      run: cd integration-tests/client-server && ../../mvnw test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m

    - name: 10 cd integration-tests/client-server && mvn test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
      shell: bash
      run: cd integration-tests/client-server && ../../mvnw test -Dtest=RedirectTest#retransmitCacheAsyncBlocking9m
