name: Quarkiverse Release

on:
  pull_request:
    types: [closed]
    paths:
      - '.github/project.yml'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    if: ${{github.event.pull_request.merged == true}}

    steps:
      - uses: radcortez/project-metadata-action@master
        name: Read project.yml
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'

      - uses: actions/checkout@v4

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Quarkus CXF release workflow"

      - name: Update latest release version in docs
        run: |
          ./mvnw -B -ntp -pl docs -am install -Denforcer.skip -Dformatter.skip -Dimpsort.skip -Dkeytool.skip -Denforce-non-deployment.skip
          if ! git diff --quiet docs/antora.yml; then
            git add docs/antora.yml
            git commit -m "Update the latest release version ${{steps.metadata.outputs.current-version}} in documentation"
          fi

      - name: Maven release ${{steps.metadata.outputs.current-version}}
        run: |
          ./mvnw -B release:prepare -Prelease -DreleaseVersion=${{steps.metadata.outputs.current-version}} -DdevelopmentVersion=${{steps.metadata.outputs.next-version}}
          ./mvnw -B release:perform -Darguments=-DperformRelease -DperformRelease -Prelease
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Sync the examples in the docs
        run: |
          ./mvnw clean install -DskipTests -Dquarkus.build.skip -pl integration-tests/client -am
          git add -A
          git commit --amend --no-edit
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Push changes to ${{github.base_ref}} branch
        run: |
          git push
          git push origin ${{steps.metadata.outputs.current-version}}

  upgrade-in-the-platform:
    strategy:
      fail-fast: false
    name: Upgrade Quarkus CXF in the platform
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: radcortez/project-metadata-action@master
        name: Read project.yml
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'

      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Await release
        run: |
          git reset --hard ${{steps.metadata.outputs.current-version}}
          ./mvnw install -DskipTests -Dquarkus.build.skip
          ./mvnw org.l2x6.org:cq-maven-plugin:1.2.3:await-release -DreleaseVersion=${{steps.metadata.outputs.current-version}}

      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Quarkus CXF release workflow"

      - name: Upgrade Quarkus CXF in Quarkus Platform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $HOME
          git checkout git@github.com:quarkusio/quarkus-platform.git -o upstream
          cd quarkus-platform
          git checkout -b quarkus-cxf-${{steps.metadata.outputs.current-version}}
          sed -i 's|<quarkus-cxf.version>[^<]*</quarkus-cxf.version>|<quarkus-cxf.version>${{steps.metadata.outputs.current-version}}</quarkus-cxf.version>|' pom.xml
          ./mvnw -Dsync
          git add -A
          git commit -m "Upgrade to Quarkus CXF ${{steps.metadata.outputs.current-version}}"
          git remote add ppalaga git@github.com:ppalaga/quarkus-platform.git
          git push ppalaga quarkus-cxf-${{steps.metadata.outputs.current-version}}
          gh pr create -B ${{steps.metadata.outputs.platform-branch}} -H quarkus-cxf-${{steps.metadata.outputs.current-version}} --title 'Upgrade to Quarkus CXF ${{steps.metadata.outputs.current-version}}' --body 'cc @ppalaga'
